# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Atualizações para npm
    directory: "/" # Localização do package.json
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pnpm" # Atualizações para pnpm
    directory: "/" # Localização do pnpm-lock.yaml
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "yarn" # Atualizações para yarn
    directory: "/" # Localização do yarn.lock
    schedule:
      interval: "weekly"
    target-branch: "develop"
